### ISSUE TITLE
ase2clr throws ERROR: write EPIPE

### ISSUE THREAD

**Issue by siiron** [kaelig/tokens2palettes-example#1]
Current setup:

Win 10 Enterprise v1709, OS Build 16299.194
node v.8.9.4
yarn v1.3.2

Cloned this repo and followed instructions. Seems like both `.ase` and `.sketchpalette` are generated just fine (tested `colors.ase` in Photoshop - don't have Sketch on Windows, but when inspecting the file, it looks good).

The ase2clr fails though:

```
yarn dist
yarn run v1.3.2
$ yarn clean
$ rimraf ./dist
$ npm-run-all dist:**
$ theo ./tokens/colors.yml --format ase,sketchpalette --setup ./theo.setup.js --dest ./dist
✏️  ase tokens created at "dist\colors.ase"
✏️  sketchpalette tokens created at "dist\colors.sketchpalette"
$ ase2clr ./dist/colors.ase ./dist/colors.clr
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at writeScript (C:\path-to\tokens2palettes-example\node_modules\ase-util\lib\exportToOSXColorList.js:15:7)
    at module.exports (C:\path-to\tokens2palettes-example\node_modules\ase-util\lib\exportToOSXColorList.js:44:3)
    at Object.<anonymous> (C:\path-to\tokens2palettes-example\node_modules\ase-util\bin\ase2clr:14:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "dist:clr" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by kaelig** [comment]
Thanks for using this repository! The [ase-util](https://www.npmjs.com/package/ase-util) is macOS-only, sorry.

> **OSX Only:** To do the conversion the tool uses OSX scripting to get a NSColorList instance, in other words it'll not work on other platforms.
